apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: user-container
        image: salaboy/worker-java:1.0.0-amd
        imagePullPolicy: Always
        env:
        - name: DAPR_HTTP_ENDPOINT
          value: http://worker-dapr.default.svc.cluster.local:3500
        - name: DAPR_GRPC_ENDPOINT
          value: http://worker-dapr.default.svc.cluster.local:50001
        - name: BASE_URL
          value: http://worker-dapr.default.svc.cluster.local
        - name: WORKER_VOTE_STATESTORE
          value: votes-statestore
        - name: WORKER_RESULTS_STATESTORE 
          value: results-statestore
        - name: WORKER_VOTE_QUERYINDEX
          value: voteIndex  
