apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo
  namespace: default
  annotations: 
    networking.knative.dev/http-protocol: "enabled"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: docker.io/salaboy/echo-java:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PUBLIC_IP
          value: echo.default.127.0.0.1.sslip.io
        - name: DAPR_HTTP_ENDPOINT
          value: http://echo-dapr.default.svc.cluster.local:3500
        - name: DAPR_GRPC_ENDPOINT
          value: http://echo-dapr.default.svc.cluster.local:50001  
        - name: ECHO_STATE_STORE
          value: votes-statestore
