---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: votes-statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: keyPrefix
    value: name 
  - name: redisHost
    value: redis.default.svc.cluster.local:6379
  - name: redisPassword
    value: ""
  - name: outboxPublishPubsub # Required
    value: "pubsub-rabbitmq"
  - name: outboxPublishTopic # Required
    value: "newVote"
  - name: outboxDiscardWhenMissingState #Optional. Defaults to false
    value: false
  - name: actorStateStore
    value: "true"
  - name: queryIndexes
    value: |
      [
        {
          "name": "voteIndex",
          "indexes": [
           {
            "key": "type",
            "type": "TEXT" 
           },
           {
            "key": "option",
            "type": "TEXT" 
           }
          ]
        }
      ]
